### ISSUE TITLE
Adicionar branch 9.5 - dev

### ISSUE THREAD

**Issue by verdanatech-luana** [verdanatech/mailanalyzer#1]
![2021-08-16_12-01](https://user-images.githubusercontent.com/86842154/129585357-f8d33b42-e725-4867-989e-876577ba1670.png)

![2021-08-16_12-02](https://user-images.githubusercontent.com/86842154/129585369-eb5aa645-95d4-44f6-ae51-d9eac0e89a13.png)

**Comment by verdanatech-luana** [comment]
9.5-dev criada.

![2021-08-16_13-41](https://user-images.githubusercontent.com/86842154/129599196-d215fd83-4992-457a-8de6-260ce2b10c9c.png)

![2021-08-16_13-42](https://user-images.githubusercontent.com/86842154/129599224-ed02af97-7cff-46c3-abc7-5e44151832ff.png)

**Comment by verdanatech-marcio** [comment]
Testado, funcionando corretamente.
![TesteMA](https://user-images.githubusercontent.com/80538863/130452143-eb7a2a0f-2ac1-46a6-8bcf-177cf63f17dd.png)
